version: 7.9.{build}
image: Visual Studio 2017


environment:
  matrix:
    #- Platform: v142
    # - Platform: v141_xp
      # archi: amd64
      # platform_input: x64
      # platform_toolchain: v141_xp

    - Platform: mingw-w64_810_X64
      platform_input: mingw
      platform_toolchain: mingw-w64_810_X64
      PYTHON: "C:\\Python38"

configuration:
    - Release
    #- Debug

install:

    - if "%Platform%"=="mingw-w64_810_X32" set PATH=C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%
    - if "%Platform%"=="mingw-w64_810_X64" set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
    #- if "%archi%" NEQ "" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%archi%" NEQ "" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    #- if "%archi%" NEQ "" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

    - ps: |
        if ($env:PLATFORM -match "mingw-w64_810_X64") {
            # if($env:PLATFORM -match "Win32") {
                # $env:Path += ";C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin"
                # $env:Path += ";C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\i686-w64-mingw32\lib"
            # }
            # if($env:PLATFORM -match "x64") {
                # $env:Path += ";C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin"
                # $env:Path += ";C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32\lib"
            # }
            # $env:Path = $env:Path.Replace('C:\Program Files\Git\usr\bin;','')
            g++ --version
            mingw32-make --version
        }


before_build:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    $generator = switch ($env:PLATFORM_TOOLCHAIN)
    {
        "v142" {"Visual Studio 16 2019"}
        "v141_xp" {"Visual Studio 15 2017"}
        "v140_xp" {"Visual Studio 14 2015"}
        "v120_xp" {"Visual Studio 12 2013"}
        "mingw-w64_810_X64" { "MinGW Makefiles"}
    }
    #not applicable with MinGW Makefiles generator
    if ($env:PLATFORM_INPUT -eq "x64" -and $env:PLATFORM_INPUT -notmatch "mingw")
    {
        $generator = "$generator Win64"
    }
    #cmake build type, depended on the used generator, see https://cmake.org/cmake/help/v3.6/variable/CMAKE_BUILD_TYPE.html#variable:CMAKE_BUILD_TYPE
    if ($env:PLATFORM_INPUT -match "mingw")
    {
        $build_type = "-DCMAKE_BUILD_TYPE=$env:CONFIGURATION"
        $build_config = ""
    }
    else
    {
        #seems vs build always needs also the debug config, choose via the config option to the build command
        $build_type = "-DCMAKE_CONFIGURATION_TYPES=""Debug;Release"" "
        $build_config = "--config $env:CONFIGURATION"
    }
    Write-Output "build_type: $build_type"
    Write-Output "build_config: $build_config"

build_script:
- cd "%APPVEYOR_BUILD_FOLDER%"\scintilla\win32
#- if "%platform_input%"=="mingw" mingw32-make depend
- if "%platform_input%"=="mingw" mingw32-make %scintilla_debug% -j%NUMBER_OF_PROCESSORS%
- if "%platform_input%"=="mingw" cd "%APPVEYOR_BUILD_FOLDER%"\PowerEditor\gcc\ & mingw32-make -j%NUMBER_OF_PROCESSORS%
- if "%archi%"=="x86" nmake -f scintilla.mak
- if "%archi%"=="amd64" nmake -f scintilla.mak

- cd "%APPVEYOR_BUILD_FOLDER%"\PowerEditor\src
- ps: |
    md _build -Force | Out-Null
    cd _build
    & cmake -G "$generator" $build_type ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config $env:CONFIGURATION 
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }


