version: 8.4.{build}
image: Visual Studio 2022


install:
    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
    - set SIGN=1
    - set NPP_CERT="%APPVEYOR_BUILD_FOLDER%"\PowerEditor\installer\test-signing.pfx
    - set NPP_CERT_PWD=Password1234
    - ps: |
        Write-Output "SIGN : $env:SIGN"
        Write-Output "NPP_CERT : $env:NPP_CERT"
        Write-Output "NPP_CERT_PWD : $env:NPP_CERT_PWD"
        Write-Output ""
        # XML validation mode
        $allowMaster = $true
        if ($allowMaster -or $env:APPVEYOR_PULL_REQUEST_NUMBER) {
            $folders_onejob = "PowerEditor/(Test|(installer/(filesForTesting|functionList)))/"
            $files_nowork = "md|txt|log|ini"
            $files_modified = @(git diff --name-only HEAD~1)
            $files_notmached = @($files_modified | Where-Object {$_ -notmatch "\.(xml|$files_nowork)$|$folders_onejob"})
            if (($files_modified.length -gt 0 -and $files_notmached.length -eq 0) -or $env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[force (xml|nowork)\]") {
                if (@($files_modified | Where-Object {$_ -notmatch "\.($files_nowork)$"}).length -eq 0 -or $env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[force nowork\]") {
                    Write-Output "Changed files on this commit don't require any additional tasks.`n"
                    Exit-AppVeyorBuild
                }
                else {
                    Write-Output "XML validation mode`n"
                    if ("$env:platform/$env:configuration" -eq "Win32/Debug") {
                        if (@($files_modified | Where-Object {$_ -match $folders_onejob}).length -eq 0) {
                            $env:Path = "$env:python_dir;$env:python_dir\Scripts;" + $env:Path
                            python -m pip install requests rfc3987 pywin32 lxml
                            python PowerEditor\Test\xmlValidator\validator_xml.py
                            if ($LastExitCode -eq 0) {
                                Write-Output "`nAll XML files are valid.`n"
                                Exit-AppVeyorBuild
                            }
                            else {
                                Write-Output "`nSome XML files are invalid.`n"
                                $host.SetShouldExit($LastExitCode)
                            }
                        }
                    }
                    else {
                        Write-Output "In XML validation mode only Win32/Debug performs the proper tasks.`n"
                        Exit-AppVeyorBuild
                    }
                }
            }
            elseif ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[xml\]" -and $env:APPVEYOR_REPO_COMMIT_MESSAGE -notmatch "\[force compile\]") {
                throw "Changed files on this commit require full build."
            }
        }


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\PowerEditor\installer
    - packageAll.bat
