name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Unicode Release]
        build_platform: [x64, Win32]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild of N++
      working-directory: PowerEditor\visual.net\
      run: msbuild notepadPlus.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v142"
